clusters = primary, secondary

primary.bootstrap.servers = broker-1:19092,broker-2:19092,broker-3:19092
secondary.bootstrap.servers = mirror-broker:19093

primary->secondary.enabled = true
secondary->primary.enabled = false

primary->secondary.topics = ledgerflow\\..*
primary->secondary.groups = ledger-service,fraud-service,notification-service

replication.factor = 1
heartbeats.topic.replication.factor = 1
checkpoints.topic.replication.factor = 1
offset-syncs.topic.replication.factor = 1

refresh.topics.interval.seconds = 10
refresh.groups.interval.seconds = 10
sync.topic.configs.enabled = true
sync.group.offsets.enabled = true
emit.heartbeats.enabled = true
emit.checkpoints.enabled = true

replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy
