security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
ssl.truststore.location=/etc/ledgerflow/security/truststore.p12
ssl.truststore.password=ledgerflow
ssl.truststore.type=PKCS12
