{
 "title": "LedgerFlow Overview",
 "tags": [
  "ledgerflow",
  "kafka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Kafka Exporters UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=\"kafka-brokers\"})",
     "legendFormat": "Kafka exporters"
    }
   ]
  },
  {
   "title": "Transaction API",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"transaction-api\"}",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Accepted Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(ledgerflow_transaction_api_requests_total{result=\"accepted\"}[5m])",
     "legendFormat": "accepted/sec"
    }
   ]
  },
  {
   "title": "Kafka Publish Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(ledgerflow_transaction_api_requests_total{result=\"kafka_publish_error\"}[5m])",
     "legendFormat": "errors/sec"
    }
   ]
  }
 ]
}